from __future__ import annotations

import math
import random
from collections.abc import Sequence
from dataclasses import dataclass
from enum import StrEnum
from statistics import fmean, median


class SamplingMode(StrEnum):
    """Method used to generate simulated trade sequences."""

    BOOTSTRAP = "bootstrap"
    SHUFFLE = "shuffle"


@dataclass(frozen=True, slots=True)
class MonteCarloConfig:
    """Configuration for a Monte Carlo simulation."""

    simulations: int = 1_000
    initial_equity: float = 10_000.0
    sample_size: int | None = None
    sampling_mode: SamplingMode = SamplingMode.BOOTSTRAP
    seed: int | None = None
    store_equity_curves: bool = False

    def __post_init__(self) -> None:
        if not isinstance(self.simulations, int):
            raise TypeError("SIMULATIONS_MUST_BE_INTEGER")

        if self.simulations <= 0:
            raise ValueError("SIMULATIONS_MUST_BE_POSITIVE")

        if not math.isfinite(self.initial_equity):
            raise ValueError("INITIAL_EQUITY_MUST_BE_FINITE")

        if self.initial_equity <= 0:
            raise ValueError("INITIAL_EQUITY_MUST_BE_POSITIVE")

        if self.sample_size is not None:
            if not isinstance(self.sample_size, int):
                raise TypeError("SAMPLE_SIZE_MUST_BE_INTEGER")

            if self.sample_size <= 0:
                raise ValueError("SAMPLE_SIZE_MUST_BE_POSITIVE")

        if not isinstance(self.sampling_mode, SamplingMode):
            raise TypeError("SAMPLING_MODE_MUST_BE_SAMPLING_MODE")

        if self.seed is not None and not isinstance(self.seed, int):
            raise TypeError("SEED_MUST_BE_INTEGER_OR_NONE")

        if not isinstance(self.store_equity_curves, bool):
            raise TypeError("STORE_EQUITY_CURVES_MUST_BE_BOOLEAN")


@dataclass(frozen=True, slots=True)
class SimulationPath:
    """Metrics generated by one simulated sequence."""

    final_equity: float
    total_return: float
    max_drawdown: float
    equity_curve: tuple[float, ...] | None = None


@dataclass(frozen=True, slots=True)
class MonteCarloResult:
    """Aggregated result from all simulated paths."""

    config: MonteCarloConfig
    paths: tuple[SimulationPath, ...]

    @property
    def final_equities(self) -> tuple[float, ...]:
        return tuple(path.final_equity for path in self.paths)

    @property
    def max_drawdowns(self) -> tuple[float, ...]:
        return tuple(path.max_drawdown for path in self.paths)

    @property
    def mean_final_equity(self) -> float:
        return float(fmean(self.final_equities))

    @property
    def median_final_equity(self) -> float:
        return float(median(self.final_equities))

    @property
    def worst_final_equity(self) -> float:
        return float(min(self.final_equities))

    @property
    def best_final_equity(self) -> float:
        return float(max(self.final_equities))

    @property
    def worst_max_drawdown(self) -> float:
        return float(max(self.max_drawdowns))

    @property
    def probability_of_loss(self) -> float:
        losing_paths = sum(
            path.final_equity < self.config.initial_equity for path in self.paths
        )
        return float(losing_paths / len(self.paths))

    def percentile_final_equity(self, percentile: float) -> float:
        """Return a nearest-rank percentile of final equity."""
        return _nearest_rank_percentile(
            self.final_equities,
            percentile,
        )

    def percentile_max_drawdown(self, percentile: float) -> float:
        """Return a nearest-rank percentile of maximum drawdown."""
        return _nearest_rank_percentile(
            self.max_drawdowns,
            percentile,
        )


class MonteCarloEngine:
    """
    Generate randomized trade sequences and simulated equity paths.

    Trade returns must be expressed as decimal returns:

        0.02  = +2%
       -0.01  = -1%
    """

    def __init__(
        self,
        config: MonteCarloConfig | None = None,
    ) -> None:
        self.config = config or MonteCarloConfig()

    def run(
        self,
        trade_returns: Sequence[float],
    ) -> MonteCarloResult:
        validated_returns = _validate_trade_returns(trade_returns)

        sample_size = (
            self.config.sample_size
            if self.config.sample_size is not None
            else len(validated_returns)
        )

        if self.config.sampling_mode is SamplingMode.SHUFFLE and sample_size != len(
            validated_returns
        ):
            raise ValueError("SHUFFLE_SAMPLE_SIZE_MUST_MATCH_RETURNS_LENGTH")

        rng = random.Random(self.config.seed)
        paths: list[SimulationPath] = []

        for _ in range(self.config.simulations):
            sampled_returns = self._sample_returns(
                validated_returns,
                sample_size,
                rng,
            )

            paths.append(self._simulate_path(sampled_returns))

        return MonteCarloResult(
            config=self.config,
            paths=tuple(paths),
        )

    def _sample_returns(
        self,
        trade_returns: tuple[float, ...],
        sample_size: int,
        rng: random.Random,
    ) -> tuple[float, ...]:
        if self.config.sampling_mode is SamplingMode.BOOTSTRAP:
            return tuple(rng.choice(trade_returns) for _ in range(sample_size))

        shuffled = list(trade_returns)
        rng.shuffle(shuffled)
        return tuple(shuffled)

    def _simulate_path(
        self,
        sampled_returns: tuple[float, ...],
    ) -> SimulationPath:
        equity = self.config.initial_equity
        peak_equity = equity
        max_drawdown = 0.0

        stored_curve: list[float] | None = (
            [equity] if self.config.store_equity_curves else None
        )

        for trade_return in sampled_returns:
            equity *= 1.0 + trade_return
            peak_equity = max(peak_equity, equity)

            current_drawdown = (peak_equity - equity) / peak_equity
            max_drawdown = max(
                max_drawdown,
                current_drawdown,
            )

            if stored_curve is not None:
                stored_curve.append(float(equity))

        total_return = (equity / self.config.initial_equity) - 1.0

        return SimulationPath(
            final_equity=float(equity),
            total_return=float(total_return),
            max_drawdown=float(max_drawdown),
            equity_curve=(tuple(stored_curve) if stored_curve is not None else None),
        )


def _validate_trade_returns(
    trade_returns: Sequence[float],
) -> tuple[float, ...]:
    if isinstance(
        trade_returns,
        (str, bytes),
    ):
        raise TypeError("TRADE_RETURNS_MUST_BE_NUMERIC_SEQUENCE")

    try:
        values = tuple(float(value) for value in trade_returns)
    except (TypeError, ValueError) as exc:
        raise TypeError("TRADE_RETURNS_MUST_BE_NUMERIC_SEQUENCE") from exc

    if not values:
        raise ValueError("TRADE_RETURNS_CANNOT_BE_EMPTY")

    for value in values:
        if not math.isfinite(value):
            raise ValueError("TRADE_RETURN_MUST_BE_FINITE")

        if value <= -1.0:
            raise ValueError("TRADE_RETURN_MUST_BE_GREATER_THAN_MINUS_ONE")

    return values


def _nearest_rank_percentile(
    values: Sequence[float],
    percentile: float,
) -> float:
    if not math.isfinite(percentile):
        raise ValueError("PERCENTILE_MUST_BE_FINITE")

    if not 0.0 <= percentile <= 100.0:
        raise ValueError("PERCENTILE_MUST_BE_BETWEEN_0_AND_100")

    ordered = sorted(float(value) for value in values)

    if percentile == 0.0:
        return float(ordered[0])

    rank = math.ceil((percentile / 100.0) * len(ordered))

    return float(ordered[rank - 1])
